### ISSUE TITLE
1606765 breaks October if no Wordpress migration config is set

### ISSUE THREAD

**Issue by mpopke** [DallasMuseumArt/OctoberFriends#5]
In the register function of Plugin.php, Log::info() is being called to record that there is no Wordpress config set for Friends. Log::info can't be called here because the register function is called before the Laravel application is fully created. When you don't have wordpress migration info set, this line will throw an exception, "Call to undefined method Illuminate\Support\Facades\Log::info()", because the Log facade isn't associated with any Log objects yet.

Do we need to log this? Even if it didn't throw an exception for those of us who aren't migrating from Wordpress, this will just fill up a line in the log pretty much every time someone sends a request to our server.

**Comment by karnold** [comment]
I'd say just remove it

—
Kristen

**Comment by mpopke** [comment]
Agreed, just wanted to make sure you weren't using it for something before I cut it.
